# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Build Start:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Start build job'
        # Default value if no value is explicitly provided
        default: false
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn clean install
